/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.pak3nuh.kotlin.playground

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
